export const teamMembers = [
  {
    name: "Kanak Kholwal",
    position: "Final Year Member",
    image: "https://i.ibb.co/GvqqSx73/3551911.jpg" ,
    linkedin: "",
    year: 4,
    github: "",
  },
  {
    name: "Akhil Jamwal",
    position: "Final Year Member",
    image: "https://i.ibb.co/84G8z3Xx/bc9fd4bd-de9b-4555-976c-8360576c6708.jpg",
    linkedin: "",
    year: 4,
    github: "",
  },
  {
    name: "Shreshta Jaiswal",
    position: "Final Year Member",
    image: "https://i.ibb.co/KzByh7ZQ/10491830.jpg",
    linkedin: "",
    year: 4,
    github: "",
  },
  {
    name: "Vatsalya Sharma",
    position: "Final Year Member",
    image: "https://i.ibb.co/84G8z3Xx/bc9fd4bd-de9b-4555-976c-8360576c6708.jpg",
    linkedin: "",
    year: 4,
    github: "",
  },
  {
    name: "Akshit Gupta",
    position: "Final Year Member",
    image: "https://i.ibb.co/84G8z3Xx/bc9fd4bd-de9b-4555-976c-8360576c6708.jpg",
    linkedin: "",
    year: 4,
    github: "",
  },
  {
    name: "Radhesh Chaudhary",
    position: "Final Year Member",
    image: "https://i.ibb.co/84G8z3Xx/bc9fd4bd-de9b-4555-976c-8360576c6708.jpg",
    linkedin: "",
    year: 4,
    github: "",
  },
  {
    name: "Aryan Shradhay",
    position: "Final Year Member",
    image: "https://i.ibb.co/84G8z3Xx/bc9fd4bd-de9b-4555-976c-8360576c6708.jpg",
    linkedin: "",
    year: 4,
    github: "",
  },
  {
    name: "Tanisha Sharma",
    position: "Final Year Member",
    image: "https://i.ibb.co/KzByh7ZQ/10491830.jpg",
    linkedin: "",
    year: 4,
    github: "",
  },
  {
    name: "Aditya Sood",
    position: "Final Year Member",
    image: "https://i.ibb.co/84G8z3Xx/bc9fd4bd-de9b-4555-976c-8360576c6708.jpg",
    linkedin: "",
    year: 4,
    github: "",
  },
  {
    name: "Sejal Jain",
    position: "Final Year Member",
    image: "https://i.ibb.co/KzByh7ZQ/10491830.jpg",
    linkedin: "",
    year: 4,
    github: "",
  },
  {
    name: "Anusha Sharma",
    position: "Final Year Member",
    image: "https://i.ibb.co/KzByh7ZQ/10491830.jpg",
    linkedin: "",
    year: 4,
    github: "",
  },
  {
    name: "Satvik",
    position: "Final Year Member",
    image: "https://i.ibb.co/84G8z3Xx/bc9fd4bd-de9b-4555-976c-8360576c6708.jpg",
    linkedin: "",
    year: 4,
    github: "",
  },
  {
    name: "Chandan Kumar",
    position: "Final Year Member",
    image: "https://i.ibb.co/84G8z3Xx/bc9fd4bd-de9b-4555-976c-8360576c6708.jpg",
    linkedin: "",
    year: 4,
    github: "",
  },
  {
    name: "Rajat",
    position: "Final Year Member",
    image: "https://i.ibb.co/84G8z3Xx/bc9fd4bd-de9b-4555-976c-8360576c6708.jpg",
    linkedin: "",
    year: 4,
    github: "",
  },
  {
    name: "Mrigesh",
    position: "Final Year Member",
    image: "https://i.ibb.co/84G8z3Xx/bc9fd4bd-de9b-4555-976c-8360576c6708.jpg",
    linkedin: "",
    year: 4,
    github: "",
  },
  {
    name: "Anurag",
    position: "Lead",
    image: "https://i.ibb.co/YrrqFV2/anuragsir.jpg",
    linkedin:
      "https://www.linkedin.com/in/anurag-varshney-6a6a4321b?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    year: 3,
    github: "",
  },
  {
    name: "Anshita Siroya",
    position: "Co Lead",
    image: "https://i.ibb.co/B2K8Zbkx/IMG-20250225-WA0007.jpg",
    linkedin: "https://www.linkedin.com/in/anshita-siroya-18a9b3256/",
    year: 3,
    github: "https://github.com/anshi0",
  },
  {
    name: "Ankit Yadav",
    position: "ML Lead",
    image: "https://i.ibb.co/DD8Q3h9C/IMG-20231014-213547-2.jpg",
    linkedin: "https://www.linkedin.com/in/ankit-yadav-38a005257/",
    year: 3,
    github: "https://github.com/02ankit482",
  },
  {
    name: "Abhishek Raj",
    position: "UI/UX Lead",
    image: "https://i.ibb.co/N22b9T4g/profile.jpg",
    linkedin: "https://www.linkedin.com/in/abhishek-raj-a09181215",
    year: 3,
    github: "https://github.com/abhishekrj02",
  },

  {
    name: "Anubhav Mishra ",
    position: "Web Team",
    image: "https://i.ibb.co/pjFDdqjk/resized-second-image.jpg",
    linkedin: "https://www.linkedin.com/in/anubhav-mi",
    year: 3,
    github: "https://github.com/Anubhav-MI",
  },
  {
    name: "Anush Saxena ",
    position: "Gang leader",
    image: "https://i.ibb.co/Jwgqm92t/Screenshot-2025-0327-014504.jpg",
    linkedin: "https://www.linkedin.com/in/anush-saxena-582047248",
    year: 3,
    github: "GitHub.com/Anush-Saxena",
  },
  {
    name: "Tanishq Chauhan",
    position: "App Team",
    image: "https://i.ibb.co/YFXnJbfm/Formal-Tanishq-photo.png",
    linkedin: "www.linkedin.com/in/tanishq-chauhan-936b25258",
    year: 3,
    github: "https://github.com/Volcandrabuzz",
  },
  {
    name: "Yatha Grover",
    position: "ML team",
    image: "https://i.ibb.co/JWkFndbv/yatha.jpg",
    linkedin: "https://www.linkedin.com/in/yatha-grover-9a7275253/",
    year: 3,
    github: "https://github.com/YATHAGROVER",
  },
  {
    name: "Prashant Tripathi",
    position: "App Team",
    image: "https://i.ibb.co/84G8z3Xx/bc9fd4bd-de9b-4555-976c-8360576c6708.jpg",
    linkedin: "https://www.linkedin.com/in/prashant-tripathi-7b7b3b1b5",
    year: 3,
    github: "https://github.com/Pt1234567",
  },
  {
    name: "Harshvardhan ",
    position: "App Team",
    image: "https://i.ibb.co/84sg2ck9/4e0229c4-fe1d-4823-996e-750d5ed30f56.jpg",
    linkedin: "",
    year: 3,
    github: "",
  },

  {
    name: "Ananya Pratap Singh ",
    position: "Executive Member",
    image:
      "https://i.ibb.co/ZpfcRpJ3/Screenshot-2025-01-28-19-50-48-34-e2d5b3f32b79de1d45acd1fad96fbb0f.jpg",
    linkedin: "",
    year: 2,
    github: "https://github.com/AnanyaPratapSingh7",
  },
  {
    name: "Aniket Chauhan",
    position: "Executive Member",
    image: "https://i.ibb.co/G3943qHP/23BEE011.jpg",
    linkedin: "",
    year: 2,
    github: "https://github.com/aniketchauhan18",
  },
  {
    name: "Anshi Jain ",
    position: "Executive Member",
    image: "https://i.ibb.co/gLSSv2gK/anshiphto.jpg",
    linkedin: "",
    year: 2,
    github: "https://github.com/Anshi-del",
  },
  {
    name: "Archisman",
    position: "Executive Member",
    image: "https://i.ibb.co/7NSS2Cvy/archiee.jpg",
    linkedin: "",
    year: 2,
    github: "https://github.com/Archisman-spec",
  },
  {
    name: "Arjun",
    position: "Executive Member",
    image: "https://i.ibb.co/dsZHGkyZ/arjunnnndsc.png",
    linkedin: "",
    year: 2,
    github: "",
  },
  {
    name: "Harshit Sethi",
    position: "Executive Member",
    image: "https://i.ibb.co/v6v8RPgH/harshit-sethi.jpg",
    linkedin: "",
    year: 2,
    github: "",
  },
  {
    name: "Ishaan Yadav",
    position: "Executive Member",
    image: "https://ibb.co/hjnrfcD",
    linkedin:
      "https://www.linkedin.com/in/ishaan-yadav-950a6327b?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    year: 2,
    github: "https://github.com/Ishaan-yadav09",
  },
  {
    name: "Ishita",
    position: "Executive Member",
    image: "https://i.ibb.co/PdPVg5R/IMG-20250313-WA0031.jpg",
    linkedin: "https://www.linkedin.com/in/ishita-bansal-57845b2a3/",
    year: 2,
    github: "https://github.com/IshitaBansal09",
  },
  {
    name: "Lokesh Kumar ",
    position: "Executive Member",
    image: "https://i.ibb.co/7tfD5k27/Pic-436-572.png",
    linkedin: "https://www.linkedin.com/in/lokesh-kumar-b92519290",
    year: 2,
    github: "https://github.com/lokesh772705",
  },
  {
    name: "Manavi Sharma ",
    position: "Executive Member",
    image: "https://i.ibb.co/yntn8MfL/IMG-7586-3.jpg",
    linkedin: "",
    year: 2,
    github: "https://github.com/manavi-24",
  },
  {
    name: "Nandini Gusain",
    position: "Executive Member",
    image: "https://i.ibb.co/jPBqVXsQ/IMG-20250326-215908.jpg",
    linkedin: "",
    year: 2,
    github: "https://github.com/Nandinigusain",
  },
  {
    name: "Pragya Sharma",
    position: "Executive Member",
    image: "https://i.ibb.co/xtjJ3wGS/IMG-20250211-WA0012.jpg",
    linkedin: "",
    year: 2,
    github: "",
  },
  {
    name: "Rahul Yadav",
    position: "Executive Member",
    image: "https://i.ibb.co/8LQCz9V6/123.jpg",
    linkedin: "",
    year: 2,
    github: "Rahul-yadavgithub (Rahul Yadav)",
  },
  {
    name: "Rishabh",
    position: "Executive Member",
    image: "https://i.ibb.co/23pxqDm7/rishab.jpg",
    linkedin: "",
    year: 2,
    github: "https://github.com/Rishabh4940",
  },
  {
    name: "Sarthak Arora",
    position: "Executive Member",
    image: "https://i.ibb.co/fznHkVtn/sarthak.jpg",
    linkedin: "",
    year: 2,
    github: "",
  },
  {
    name: "Sauren Sharma",
    position: "Executive Member",
    image: "https://i.ibb.co/WN2x2nvJ/IMG-9480.jpg",
    linkedin:
      "https://www.linkedin.com/in/sauren-sharma?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app",
    year: 2,
    github: "https://github.com/Dralt03",
  },
  {
    name: "Soham Juneja ",
    position: "Executive Member",
    image: "https://i.ibb.co/LhrWWKX7/Soham-Juneja.jpg",
    linkedin: "",
    year: 2,
    github: "https://github.com/SohamJuneja",
  },
  {
    name: "Ujjawal Maheshwari ",
    position: "Executive Member",
    image: "https://i.ibb.co/sdqN1nnL/Passport-size-UM-1.jpg",
    linkedin: "",
    year: 2,
    github: "https://github.com/Ujjawall12",
  },
  {
    name: "Ujjwal Kumar",
    position: "Executive Member",
    image: "https://i.ibb.co/99yWCrN6/20241014092300563.jpg",
    linkedin: "",
    year: 2,
    github: "https://github.com/contributorsambhav",
  },
  {
    name: "Virendra Sahu ",
    position: "Executive Member",
    image: "https://i.ibb.co/BVcLzQq4/IMG20241014120036.jpg",
    linkedin: "https://www.linkedin.com/in/virendra-sahu-a0a989291/",
    year: 2,
    github: "https://github.com/sahu-virendra-1908",
  },
  {
    name: "Sambhav",
    position: "Executive Member",
    image: "https://i.ibb.co/tMjFXcXm/IMG-20250326-223526.jpg",
    linkedin: "",
    year: 2,
    github: "",
  },
  {
    name: "Harsh Saini",
    position: "Executive Member",
    image: "https://i.ibb.co/F4DXwz47/IMG-0415.jpg",
    linkedin: "",
    year: 2,
    github: "",
  },
  {
    name: "Raman Bansal",
    position: "Volunteer",
    image: "https://i.ibb.co/4ws9LVGn/prof.png",
    linkedin: "https://www.linkedin.com/in/-raman-bansal",
    year: 1,
    github: "https://github.com/ramanbansal1",
  },
  {
    name: "SAURABH CHAUHAN",
    position: "Volunteer",
    image: "https://i.ibb.co/0ygqwzz5/IMG-20230529-164157.jpg",
    linkedin: "https://www.linkedin.com/in/saurabh-chauhan-a96413323/",
    year: 1,
    github: "https://github.com/Saurabh-1785",
  },
  {
    name: "Prashant Bahuguna",
    position: "Volunteer",
    image: "https://i.ibb.co/LDLjJFQc/IMG-20230223-WA0006.jpg",
    linkedin: "https://www.linkedin.com/in/prashant-bahuguna-45559130b",
    year: 1,
    github: "https://github.com/devprashant19",
  },
  {
    name: "Prashant Thakur ",
    position: "Volunteer",
    image: "https://i.ibb.co/HT4FN7CM/IMG-20250311-WA0090.jpg",
    linkedin: "https://www.linkedin.com/in/prashant-thakur-046678322/",
    year: 1,
    github: "https://github.com/Prashant-thakur77",
  },
  {
    name: "Lakshay",
    position: "Volunteer",
    image: "https://i.ibb.co/zWKc8tCL/24BCS065.jpg",
    linkedin: "https://www.linkedin.com/in/lakshay-deol-603b532b0/",
    year: 1,
    github: "",
  },
  {
    name: "Abhishika Choudhary",
    position: "Volunteer",
    image: "https://i.ibb.co/DHzr2zw3/mememe.jpg",
    linkedin: "https://www.linkedin.com/in/abhishika-choudhary-85434831b/",
    year: 1,
    github: "https://github.com/ika12345",
  },
  {
    name: "Prasmeta Behera",
    position: "Volunteer",
    image: "https://i.ibb.co/1NbDSg6/IMG-0207.jpg",
    linkedin: "www.linkedin.com/in/prasmeta-behera-11582b2a7",
    year: 1,
    github: "https://github.com/Prasmeta",
  },
  {
    name: "Shravani Vaishnav",
    position: "Volunteer",
    image: "https://i.ibb.co/99rF3VXv/IMG-20250315-WA0013.jpg",
    linkedin:
      "https://www.linkedin.com/in/shravani-vaishnav-90a8ab304?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    year: 1,
    github: "https://github.com/Shravanivaishnav",
  },
  {
    name: "Anshu Kumari",
    position: "Volunteer",
    image: "https://i.ibb.co/9mWZQY6W/img.jpg",
    linkedin: "https://www.linkedin.com/in/anshu-kumari-903948324/",
    year: 1,
    github: "https://github.com/Anshudh",
  },
  {
    name: "Ayush Chauhan",
    position: "Volunteer",
    image: "https://i.ibb.co/WNyBwgMv/DSC-site.jpg",
    linkedin: "https://www.linkedin.com/in/ayush-chauhan-071918353",
    year: 1,
    github: "https://github.com/CoderChaos108",
  },
  {
    name: "Somya Verma",
    position: "Volunteer",
    image: "https://i.ibb.co/gnQGwCP/DSC-SITE.jpg",
    linkedin: "https://www.linkedin.com/in/somya-verma-nith",
    year: 1,
    github: "https://github.com/somya7verma",
  },
  {
    name: "Zulikha Banoo",
    position: "Volunteer",
    image: "https://i.ibb.co/S4n69xfN/20240903-130726.jpg",
    linkedin:
      "https://www.linkedin.com/in/zulikha-banoo-a636b7328?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    year: 1,
    github: "https://github.com/zulikha-star",
  },
  {
    name: "Harsh Bhushan Pathak",
    position: "Volunteer",
    image: "https://i.ibb.co/HL32JpWP/IMG-20250111-WA0080-2.jpg",
    linkedin: "https://www.linkedin.com/in/harsh-bhushan-pathak-91590a312",
    year: 1,
    github: "https://github.com/harshbpathak",
  },
  {
    name: "Anshika Sharma",
    position: "Volunteer",
    image: "https://i.ibb.co/r2GPMJ25/AS.jpg",
    linkedin:
      "https://www.linkedin.com/in/anshika-sharma-135a47316?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    year: 1,
    github: "https://github.com/Anshika17S",
  },
  {
    name: "Chetan",
    position: "Volunteer",
    image: "https://ibb.co/bnLKwqM",
    linkedin:
      "https://www.linkedin.com/in/chetan-nith-6218b3329?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app ",
    year: 1,
    github: "https://github.com/chetan208",
  },
  {
    name: "Sarthak",
    position: "Volunteer",
    image: "https://i.ibb.co/Rk14MtB0/24BCS101.jpg",
    linkedin:
      "https://www.linkedin.com/in/sarthak-sharma-643706285?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    year: 1,
    github: "https://github.com/Sarthak9291",
  },
  {
    name: "Puneet Yadav",
    position: "Volunteer",
    image: "https://i.ibb.co/23rsD79X/Puneet.jpg",
    linkedin: "https://github.com/puneetnith28",
    year: 1,
    github: "https://github.com/puneetnith28",
  },
  {
    name: "Jatin Sharma",
    position: "Volunteer",
    image: "https://github.com/Jatin0057",
    linkedin: "https://www.linkedin.com/in/jatin-sharma-b9b91030b",
    year: 1,
    github: "",
  },
  {
    name: "Deep Sharma",
    position: "Volunteer",
    image: "https://i.ibb.co/5xsQhmcB/20240816-121155-2.jpg",
    linkedin: "https://www.linkedin.com/in/deep-sharma-015146348",
    year: 1,
    github: "https://github.com/Deep-Sharma28",
  },
  {
    name: "Pradyuman",
    position: "Volunteer",
    image:
      "https://i.ibb.co/B2Gz8Gz2/Whats-App-Image-2025-01-29-at-10-36-10-f8b155ec.jpg",
    linkedin: "https://www.linkedin.com/in/pradyuman-sharma-01832631b/",
    year: 1,
    github: "https://github.com/its-me-meax",
  },
  {
    name: "Harshit",
    position: "Volunteer",
    image: "https://i.ibb.co/1tkzryGV/24-BCS049.jpg",
    linkedin:
      "https://www.linkedin.com/in/harshit-b43a60325?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    year: 1,
    github: "https://github.com/Harshit82198",
  },
  {
    name: "Arnav Chhabra",
    position: "Third Year Member",
    image: "https://i.ibb.co/4gKJSCc9/arnavsir.jpg",
    linkedin: "",
    year: 3,
    github: "",
  },
  {
    name: "Harshit Mahajan",
    position: "Third Year Member",
    image: "https://i.ibb.co/93f2CNng/harshitmahajan.jpg",
    linkedin: "",
    year: 3,
    github: "",
  },
  {
    name: "Preyanshu Mishra",
    position: "Third Year Member",
    image: "https://i.ibb.co/jvHWNH2M/preyanshusir.jpg",
    linkedin: "",
    year: 3,
    github: "",
  }
];
